=== cbaakman/mrs/config/m6-config.dtd
<!ELEMENT m6-config (directories,tools,users,servers,formats,parsers,databanks)>

<!ELEMENT directories (directory+)>
<!ELEMENT directory (#PCDATA)>
<!ATTLIST directory id ID #REQUIRED>
	
<!ELEMENT tools (tool+)>
<!ELEMENT tool (#PCDATA)>
<!ATTLIST tool id ID #REQUIRED>
	
<!ELEMENT users (user+)>
<!ELEMENT user (#PCDATA)>
<!ATTLIST user name ID #REQUIRED
			   realm CDATA #REQUIRED
			   password CDATA #REQUIRED>
	
<!ELEMENT servers (server+)>
<!ELEMENT server (admin?,base-url?,web-service*,docroot?,dbs?,blast-dbs?)+>
<!ATTLIST server addr NMTOKEN #REQUIRED
				 port NMTOKEN #REQUIRED>
<!ELEMENT admin EMPTY>
<!ATTLIST admin realm CDATA #REQUIRED>
<!ELEMENT base-url (#PCDATA)>
<!ELEMENT web-service EMPTY>
<!ATTLIST web-service service (search|blast) #REQUIRED
					  ns CDATA #REQUIRED
					  location CDATA #REQUIRED>
<!ELEMENT docroot (#PCDATA)>
<!ELEMENT dbs (db+)>
<!ELEMENT db (#PCDATA)>
<!ATTLIST db name CDATA #IMPLIED>
<!ELEMENT blast-dbs (db+)>
	
<!ELEMENT formats (format+)>
<!ELEMENT format (link*)>
<!ATTLIST format id NMTOKEN #REQUIRED
				 script CDATA #IMPLIED
				 stylesheet CDATA #IMPLIED>
<!ELEMENT link EMPTY>
<!ATTLIST link regex CDATA #REQUIRED
			   db CDATA #REQUIRED
			   id CDATA #REQUIRED
			   ix CDATA "id"
			   anchor CDATA #IMPLIED>
	
<!ELEMENT parsers (parser+)>
<!ELEMENT parser (index|add-link)+>
<!ATTLIST parser id NMTOKEN #REQUIRED
				 chunk CDATA #REQUIRED>
<!ELEMENT index EMPTY>
<!ATTLIST index name NMTOKEN #REQUIRED
				type (string|text|number) #REQUIRED
				xpath CDATA #REQUIRED
				attr (true|false) "false"
				unique (true|false) "false">
<!ELEMENT add-link EMPTY>
<!ATTLIST add-link xpath CDATA #REQUIRED
				   db CDATA #REQUIRED
				   id CDATA #REQUIRED>
	
<!ELEMENT databanks (databank+)>
<!ELEMENT databank (aliases?,name?,info?,source,filter?)>
<!ATTLIST databank id ID #REQUIRED
				   parser NMTOKEN #REQUIRED
				   update (never|daily|weekly|monthly) "never"
				   format NMTOKEN #IMPLIED>
<!ELEMENT aliases (alias+)>
<!ELEMENT alias (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ATTLIST source fetch CDATA #IMPLIED
				 delete (true|false) "false">
<!ELEMENT filter (#PCDATA)>

=== cbaakman/mrs/config/m6-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE m6-config SYSTEM "http://mrs.cmbi.ru.nl/dtd/m6-config.dtd">
<m6-config>
	
	<!-- Paths where all the data and files are stored -->
	<directories>
		<directory id="mrs">/data/mrs</directory>
		<directory id="raw">/data/raw</directory>
		<directory id="blast">/data/blast-cache</directory>
		<directory id="parser">/home/maarten/projects/m6/parsers</directory>
	</directories>

	<!-- Tools section, specify external executables used by M6 -->
	<tools>
		<tool id="clustalo">C:\Users\maarten\bin\clustal-omega\clustalo.exe</tool>
	</tools>
	
	<!-- Users section -->
	<users>
		<user name="scott" realm="M6 Administrator" password="b92ff7d60b994c8a0d2941ad9349e841"/>
	</users>

	<!-- Servers section, you can configure multiple servers but their addr+port
		 should be unique, of course. -->
	<servers>
		<server addr="0.0.0.0" port="18090">
			<admin realm="M6 Administrator"/>
			<base-url>http://localhost:18090/</base-url>
			<web-service service="search" ns="http://mrs.cmbi.ru.nl/mrsws/search" location="mrsws/search" />
			<web-service service="blast" ns="http://mrs.cmbi.ru.nl/mrsws/blast" location="mrsws/blast" />
			<docroot>./docroot/</docroot>
			<dbs>
				<db>embl</db>
				<db>enzyme</db>
				<db>omim</db>
				<db>pdbfinder</db>
				<db>sprot</db>
				<db>trembl</db>
				<db>genbank</db>
				<db>refseq</db>
				<db>taxonomy</db>
				<db>go</db>
				<db>interpro</db>
				<db>pdb</db>
				<db>dssp</db>
				<db>hssp</db>
				<db>gene</db>
				<db>pfama</db>
				<db>pfamb</db>
				<db>pfamseed</db>
				<db>prints</db>
				<db>prosite</db>
				<db>prosite_doc</db>
				<db>rebase</db>
				<db>unigene</db>
				<db>pmc</db>
			</dbs>
			
			<blast-dbs>
				<db>sprot</db>
				<db>trembl</db>
				<db name="Uniprot">uniprot</db>
				<db>pdb</db>
			</blast-dbs>
		</server>
	</servers>

	<!-- Formats section, formats are used to add links to entries and
		 to link a JavaScript pretty printer -->
	<formats>
		<format id="omim" script="scripts/omim.js">
			<link regex="(?&lt;=\()(?:[^();]+?; )?(\d{6})(?:\.(\d{4}))?(?=\))" db="omim" ix="id" id="$1" anchor="$2"/>
		</format>
		
		<format id="uniprot" script="scripts/uniprot.js">
			<link regex="(?&lt;=DR   EMBL; )(\S+)(?=;)" db="embl" ix="id" id="$1"/>
			<link regex="(?&lt;=DR   PDB; )(\S+)(?=;)" db="pdb" ix="id" id="$1"/>
			<link regex="(?&lt;=DR   RefSeq; )(?:(\S+)\.\d+)(?=;)" db="refseq" ix="id" id="$1"/>
			<link regex="(?&lt;=DR   UniGene; )(\S+)(?=;)" db="unigene" ix="id" id="$1"/>
			<link regex="(?&lt;=DR   GO; )GO:(\S+)(?=;)" db="go" ix="id" id="$1"/>
			<link regex="(?&lt;=DR   InterPro; )(\S+)(?=;)" db="interpro" ix="id" id="$1"/>
			<link regex="(?&lt;=DR   Pfam; )(\S+)(?=;)" db="pfama" ix="ac" id="$1"/>
			<link regex="(?&lt;=DR   PRINTS; )(\S+)(?=;)" db="prints" ix="id" id="$1"/>
			<link regex="(?&lt;=DR   PROSITE; )(\S+)(?=;)" db="prosite" ix="ac" id="$1"/>
			<link regex="(?&lt;=DR   MIM; )(\S+)(?=;)" db="omim" ix="id" id="$1"/>
		</format>
	
		<format id="embl" script="scripts/embl.js"/>
	
		<format id="enzyme">
			<link regex="([A-Z]+[A-Z0-9]+)(?=, )" db="sprot" ix="ac" id="$1"/>
		</format>
	
		<format id="taxonomy">
			<link regex="(?&lt;=^PARENT ID                 : )(\d+)" ix="id" id="$1" db="taxonomy"/>
		</format>
		
		<format id="interpro" stylesheet="interpro.xslt"/>
		<format id="gene" stylesheet="gene.xslt"/>
		<format id="pmc" stylesheet="ViewNLM-v2.3.xsl"/>
	
		<format id="stockholm">
			<link regex="^(?:#=GF DR\s+PFAMA;\s)(\S+)(?=;)" db="pfama" ix="id" id="$1"/>
			<link regex="^(?:#=GF DR\s+PFAMB;\s)(\S+)(?=;)" db="pfamb" ix="id" id="$1"/>
			<link regex="^(?:#=GF DR\s+PDB;\s)(\S+)(?=;)" db="pdb" ix="id" id="$1"/>
			<link regex="^(?:#=GF DR\s+PROSITE;\s)(\S+)(?=;)" db="prosite" ix="id" id="$1"/>
			<link regex="^(?:#=GF DR\s+INTERPRO;\s)(\S+)(?=;)" db="interpro" ix="id" id="$1"/>
			<link regex="^(?:#=GS .+?AC )([0-9A-Z]+)" db="uniprot" ix="ac" id="$1"/>
			<link regex="^(?:#=GS .+?DR PDB; )([0-9A-Z]{4})" db="pdb" ix="id" id="$1"/>
		</format>
	</formats>
	
	<!-- Parsers section, parsers in this section are for XML databanks only
		 and are XPath based. For huge databanks you're probably better off
		 writing a Perl parser since XPath processing is relatively bit slow. -->
	
	<parsers>
		<parser id="pmc" chunk="/article">
			<index name="id" type="string" xpath="/article/front/article-meta/article-id[@pub-id-type=&quot;pmc&quot;]" attr="true"/> <!-- really, in pmc id is not unique...  unique="true"  -->
			<index name="pmid" type="string" xpath="/article/front/article-meta/article-id[@pub-id-type=&quot;pmid&quot;]"/>
			<index name="doi" type="string" xpath="/article/front/article-meta/article-id[@pub-id-type=&quot;doi&quot;]"/>
			<index name="subject" type="text" xpath="/article/front/article-meta/article-categories/subj-group[@subj-group-type=&quot;heading&quot;]/subject"/>
			<index name="title" type="text" xpath="/article/front/article-meta/title-group/article-title" attr="true"/>
			<index name="authors" type="text" xpath="/article/front/article-meta/contrib-group/contrib/name/*"/>
			<index name="aff" type="text" xpath="/article/front/article-meta/aff"/>
			<index name="abstract" type="text" xpath="/article/front/article-meta/abstract"/>
			<index name="body" type="text" xpath="/article/body"/>
		</parser>
	
	<!--	<parser id="gene" chunk="/Entrezgene-Set/Entrezgene">-->
	<!--		<index name='id'		type="string"	xpath='Entrezgene_track-info/Gene-track/Gene-track_geneid'-->
	<!--			   attr="true"		/>-->
	<!--		<index name='title'		type="text"		xpath='Entrezgene_prot/Prot-ref/Prot-ref_name/Prot-ref_name_E'-->
	<!--			   attr="true"	/>-->
	<!--		<index name='text'		type='text'		xpath='.//*' />-->
	<!--	</parser>-->
	
		<parser id="interpro" chunk="/interprodb/interpro">
			<index name="id" type="string" xpath="@id" attr="true" unique="true"/>
			<index name="title" type="text" xpath="name" attr="true"/>
			<index name="type" type="string" xpath="@type"/>
			<index name="name" type="string" xpath="@short_name"/>
	
			<!-- Everything else (all nodes that are not 'name') -->
			<index name="text" type="text" xpath="*[name() != &quot;name&quot;]"/>
	
			<!-- All attributes -->
			<index name="attr" type="text" xpath=".//@*"/>
			
			<add-link xpath="db_xref" db="@db" id="@dbkey"/>
		</parser>
	</parsers>

	<!-- And finally, the databanks section -->
	<databanks>
		<databank id="pdbfinder" parser="pdbfinder">
			<aliases>
				<alias>pdbfinder2</alias>
			</aliases>
			<name>PDBFINDER</name>
			<source fetch="ftp://ftp.cmbi.ru.nl/pub/molbio/data/pdbfinder2>pdbfinder2">/PDBFIND2.TXT.gz</source>
		</databank>
		
		<!-- omim -->
		<databank id="omim" parser="omim" format="omim">
			<aliases>
				<alias>MIM</alias>
			</aliases>
			<name>OMIM - Online Mendelian Inheritance in Manâ„¢</name>
			<info>http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?db=OMIM</info>
			<source fetch="ftp://ftp.ncbi.nih.gov/repository/">OMIM/ARCHIVE/omim.txt.Z</source>
		</databank>
		
		<databank id="embl" parser="embl" format="embl">
			<name>EMBL</name>
			<info>http://www.ebi.ac.uk/embl/index.html</info>
			<source>embl_release/*.dat.gz</source>
		</databank>
	
		<databank id="embl-con" parser="embl">
			<name>EMBL Constructed</name>
			<info>http://www.ebi.ac.uk/embl/index.html</info>
			<source>embl/rel_con_*.dat.gz</source>
		</databank>
	
		<databank id="embl-est" parser="embl">
			<name>EMBL Expressed Sequence Tag</name>
			<info>http://www.ebi.ac.uk/embl/index.html</info>
			<source>embl/rel_est_*.dat.gz</source>
		</databank>
	
		<databank id="embl-gss" parser="embl">
			<name>EMBL Genome Sequence Scan</name>
			<info>http://www.ebi.ac.uk/embl/index.html</info>
			<source>embl/rel_gss_*.dat.gz</source>
		</databank>
	
		<databank id="embl-htc" parser="embl">
			<name>EMBL High Throughput CDNA sequencing</name>
			<info>http://www.ebi.ac.uk/embl/index.html</info>
			<source>embl/rel_htc_*.dat.gz</source>
		</databank>
	
		<databank id="embl-htg" parser="embl">
			<name>EMBL High Throughput Genome sequencing</name>
			<info>http://www.ebi.ac.uk/embl/index.html</info>
			<source>embl/rel_htg_*.dat.gz</source>
		</databank>
	
		<databank id="embl-pat" parser="embl">
			<name>EMBL Patents</name>
			<info>http://www.ebi.ac.uk/embl/index.html</info>
			<source>embl/rel_pat_*.dat.gz</source>
		</databank>
	
		<databank id="embl-std" parser="embl">
			<name>EMBL Standard</name>
			<info>http://www.ebi.ac.uk/embl/index.html</info>
			<source>embl/rel_std_*.dat.gz</source>
		</databank>
	
		<databank id="embl-sts" parser="embl">
			<name>EMBL Sequence Tagged Site</name>
			<info>http://www.ebi.ac.uk/embl/index.html</info>
			<source>embl/rel_sts_*.dat.gz</source>
		</databank>
	
		<databank id="embl-tsa" parser="embl">
			<name>EMBL Transcriptome Shotgun Assembly</name>
			<info>http://www.ebi.ac.uk/embl/index.html</info>
			<source>embl/rel_tsa_*.dat.gz</source>
		</databank>
	
		<databank id="embl-wgs" parser="embl">
			<name>EMBL Whole Genome Shotgun</name>
			<info>http://www.ebi.ac.uk/embl/index.html</info>
			<source>embl/rel_wgs_*.dat.gz</source>
		</databank>
	
		<databank id="enzyme" parser="enzyme" format="enzyme">
			<name>Enzyme</name>
			<info>http://ca.expasy.org/enzyme/</info>
			<source fetch="ftp://ftp.ebi.ac.uk/pub/databases">enzyme/enzyme.dat</source>
		</databank>
	
		<databank id="sprot" parser="uniprot" format="uniprot">
			<aliases>
				<alias>uniprot</alias>
			</aliases>
			<name>SwissProt</name>
			<info>http://www.uniprot.org/</info>
			<source fetch="ftp://ftp.ebi.ac.uk/pub/databases/">uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz</source>
		</databank>
	
		<databank id="trembl" parser="uniprot" format="uniprot">
			<aliases>
				<alias>uniprot</alias>
			</aliases>
			<name>TrEMBL</name>
			<info>http://www.uniprot.org/</info>
			<source fetch="ftp://ftp.ebi.ac.uk/pub/databases/">uniprot/current_release/knowledgebase/complete/uniprot_trembl.dat.gz</source>
		</databank>
